"""
pip install mido
python extract_corpus.py

put .mid files in same folder as this script,
update the FILES dict below with the names
"""

import mido
import json

# CONFIG
FILES = {
    "forest": "AForest.mid",
    "atmosphere": "Atmosphere.mid",
    "belalugosi": "BelaLugosi.mid",
    "blackcelebration": "BlackCelebration.mid",
    "blacknoone": "BlackNoOne.mid",
    "blackplanet": "BlackPlanet.mid",
    "christianwoman": "ChristianWoman.mid",
    "darkentries": "DarkEntries.mid",
    "disintegration": "Disintegration.mid",
    "hanginggarden": "HangingGarden.mid",
    "inyourroom": "InYourRoom.mid",
    "itsasin": "ItsASin.mid",
    "joinmeindeath": "JoinMeInDeath.mid",
    "killingmoon": "KillingMoon.mid",
    "lovelikeblood": "LoveLikeBlood.mid",
    "notinlove": "NotInLoveRobert.mid",
    "sacrifice": "Sacrifice.mid",
    "shesellssanctuary": "SheSellsSanctuary.mid",
    "spellbound": "Spellbound.mid",
    "stripped": "Stripped.mid"
}

# EXTRACTION
def extract_melody(path):
    """
    parse a midi file and return note sequence from melody track
    (skip drums, picks non-drum track w/ most notes, returns a flat list of midi pitch numbers)
    """
    mid = mido.MidiFile(path)
    tracks = []

    for track in mid.tracks:
        notes = []
        pending = {} # pitch -> tick, for matching note_on to note_off
        is_drum = False
        tick = 0

        for msg in track:
            tick += msg.time

            # channel 9 = drums, skip whole track
            if msg.type == 'note_on' and msg.channel == 9:
                is_drum = True
            # note pressed
            if msg.type == 'note_on' and msg.velocity > 0 and msg.channel != 9:
                pending[msg.note] = tick
            # note released (note_off, or note_on with velocity 0)
            elif msg.type in ('note_off', 'note_on') and msg.channel != 9:
                if msg.note in pending:
                    notes.append(msg.note)
                    del pending[msg.note]
        
        if not is_drum and notes:
            tracks.append(notes)
    
    if not tracks:
        return []

    # pick track w most notes (most likely to be melody)
    return max(tracks, key=len)

# WRITE TO CORPUS.JS:
lines = []
for name, filename in FILES.items():
    print(f"Extracting {filename}...")
    notes = extract_melody(filename)
    print(f"  --> {len(notes)} notes extracted")
    lines.append(f"  {name}: {json.dumps(notes)},")

output = (
    "// corpus.js\n"
    "// Auto-generated by extract_corpus.py -- do not edit by hand.\n"
    "// Pre-extracted note sequences from MIDI files.\n"
    "const CORPUS = {\n"
    + "\n".join(lines) +
    "\n};\n"
)

with open("../corpus.js", "w") as f:
    f.write(output)

total = sum(len(extract_melody(p)) for p in FILES.values())
print(f"\nDone! corpus.js written -- {len(FILES)} songs, check the file.")